### ISSUE TITLE
AppCenter build failed 

### ISSUE THREAD

**Issue by minaairsupport** [Plac3hold3r/PH.Wdullaer.Materialdatetimepicker#5]
I got this error while I am trying build my app over AppCenter 

```
Errors in /Users/runner/runners/2.165.2/work/1/s/AgentWay.Android/AgentWay.Android.csproj
    NU1107: Version conflict detected for Xamarin.Android.Support.Core.UI. Install/reference Xamarin.Android.Support.Core.UI 28.0.0.3 directly to project AgentWay.Android to resolve this issue.
     AgentWay.Android -> Microsoft.AppCenter.Push 3.0.0 -> Xamarin.Android.Support.v7.MediaRouter 28.0.0.3 -> Xamarin.Android.Support.v7.AppCompat 28.0.0.3 -> Xamarin.Android.Support.Fragment 28.0.0.3 -> Xamarin.Android.Support.Core.UI (= 28.0.0.3)
     AgentWay.Android -> PH.Wdullaer.Materialdatetimepicker 2.364.0 -> Xamarin.Android.Support.v13 27.0.2.1 -> Xamarin.Android.Support.Core.UI (= 27.0.2.1).
```

**Comment by Plac3hold3r** [comment]
@minaairsupport the issue is that there is conflict in versions of Android Support libraries between the two packages. As Material DateTime picker never added support for v28 they went straight to AndroidX, therefore there was no mapped version for Xamarin wrapped support libraries v28.

That being said to work around this issue you can force the installation of the conflicting package to use the highest package by explicitly including it in your project.

i.e. install `Xamarin.Android.Support.Core.UI v28.0.0.3` NuGet package

**Comment by minaairsupport** [comment]
yea I see you prelease version used AndroidX, but why its not stable yet

**Comment by Plac3hold3r** [comment]
@minaairsupport I have now updated the preview package to use the latest Xamarin AndroidX packages as well as support the latest version of Material Datetime Picker.

The AndroidX support packages can be found under version 3.x.x (the current latest 3.423.0).

**Comment by Plac3hold3r** [comment]
@minaairsupport let me know if you are still having issues
